from .root import router as root_router
from .thing import router as thing_router
from .location import router as location_router
from .historical_location import router as historical_location_router
from .datastream import router as datastream_router
from .sensor import router as sensor_router
from .observed_property import router as observed_property_router
from .observation import router as observation_router
from .feature_of_interest import router as feature_of_interest_router
from .resolver import router as resolver_router
