from .thing import create_test_thing
from .location import create_test_location
from .historical_location import create_test_historical_location
from .sensor import create_test_sensor
from .observed_property import create_test_observed_property
from .datastream import create_test_datastream
from .feature_of_interest import create_test_feature_of_interest
from .observation import create_test_observation
