# Generated by Django 4.2 on 2026-02-06 21:07

from django.db import migrations, models
import django.db.models.deletion
import sensorthings.versions.v1_1.backends.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datastream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=sensorthings.versions.v1_1.backends.django.models.uuid7_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("unit_of_measurement", models.JSONField()),
                (
                    "observation_type",
                    models.TextField(
                        choices=[
                            (
                                "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
                                "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
                            )
                        ]
                    ),
                ),
                ("properties", models.JSONField(blank=True, null=True)),
                ("observed_area", models.JSONField(blank=True, null=True)),
                ("phenomenon_time_begin", models.DateTimeField(blank=True, null=True)),
                ("phenomenon_time_end", models.DateTimeField(blank=True, null=True)),
                ("result_time_begin", models.DateTimeField(blank=True, null=True)),
                ("result_time_end", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureOfInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=sensorthings.versions.v1_1.backends.django.models.uuid7_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                (
                    "encoding_type",
                    models.TextField(
                        choices=[("application/geo+json", "application/geo+json")]
                    ),
                ),
                ("feature", models.JSONField()),
                ("properties", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Features of Interest",
            },
        ),
        migrations.CreateModel(
            name="ObservedProperty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=sensorthings.versions.v1_1.backends.django.models.uuid7_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("definition", models.TextField()),
                ("description", models.TextField()),
                ("properties", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Observed Properties",
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=sensorthings.versions.v1_1.backends.django.models.uuid7_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                (
                    "encoding_type",
                    models.TextField(
                        choices=[
                            ("application/pdf", "application/pdf"),
                            (
                                "http://www.opengis.net/doc/IS/SensorML/2.0",
                                "http://www.opengis.net/doc/IS/SensorML/2.0",
                            ),
                            ("text/html", "text/html"),
                        ]
                    ),
                ),
                ("metadata", models.TextField()),
                ("properties", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=sensorthings.versions.v1_1.backends.django.models.uuid7_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("properties", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=sensorthings.versions.v1_1.backends.django.models.uuid7_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phenomenon_time_begin", models.DateTimeField()),
                ("phenomenon_time_end", models.DateTimeField(blank=True, null=True)),
                ("result", models.FloatField()),
                ("result_time", models.DateTimeField()),
                ("result_quality", models.JSONField(blank=True, null=True)),
                ("valid_time_begin", models.DateTimeField(blank=True, null=True)),
                ("valid_time_end", models.DateTimeField(blank=True, null=True)),
                ("parameters", models.JSONField(blank=True, null=True)),
                (
                    "datastream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="sensorthings_v1_1_django_backend.datastream",
                    ),
                ),
                (
                    "feature_of_interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="sensorthings_v1_1_django_backend.featureofinterest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=sensorthings.versions.v1_1.backends.django.models.uuid7_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                (
                    "encoding_type",
                    models.TextField(
                        choices=[("application/geo+json", "application/geo+json")],
                        default="application/geo+json",
                    ),
                ),
                ("location", models.JSONField()),
                ("properties", models.JSONField(blank=True, null=True)),
                (
                    "things",
                    models.ManyToManyField(
                        blank=True,
                        related_name="locations",
                        to="sensorthings_v1_1_django_backend.thing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=sensorthings.versions.v1_1.backends.django.models.uuid7_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time", models.DateTimeField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_locations",
                        to="sensorthings_v1_1_django_backend.location",
                    ),
                ),
                (
                    "thing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_locations",
                        to="sensorthings_v1_1_django_backend.thing",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Historical Locations",
            },
        ),
        migrations.AddField(
            model_name="datastream",
            name="observed_property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datastreams",
                to="sensorthings_v1_1_django_backend.observedproperty",
            ),
        ),
        migrations.AddField(
            model_name="datastream",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datastreams",
                to="sensorthings_v1_1_django_backend.sensor",
            ),
        ),
        migrations.AddField(
            model_name="datastream",
            name="thing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datastreams",
                to="sensorthings_v1_1_django_backend.thing",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicallocation",
            constraint=models.UniqueConstraint(
                fields=("thing", "time"), name="unique_historical_location_per_time"
            ),
        ),
    ]
