# Generated by Django 4.2 on 2026-02-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensorthings_v1_1_django_backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallocation",
            name="location",
        ),
        migrations.AddField(
            model_name="historicallocation",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="historical_locations",
                to="sensorthings_v1_1_django_backend.location",
            ),
        ),
    ]
